name: audiotestproject
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter_volume_controller:
  toggle_switch: ^2.1.0
  flutter:
    sdk: flutter
  audioplayers: ^5.2.1

  cupertino_icons: ^1.0.2
  flutter_dtmf: ^3.0.2
  provider: ^6.1.1
  record: ^5.0.4
  fl_chart: ^0.66.1
  fftea: ^1.5.0
  path_provider: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter:
  generate: true
  uses-material-design: true